### ISSUE TITLE
[Desktop v1.0] Play doesn't work on Mac OS X

### ISSUE THREAD

**Issue by AdrianMastronardi** [Musicoin/desktop#170]
Hi,
I can't make the new desktop v1.0 to reproduce music. I'm attaching a video where you can see that even when I have music on my playlist, it never start playing. Tried to close and open again, restarting laptop, etc. Neither worked.

You can see the video here: https://youtu.be/bltJmFccYp8

Regards,
AM

**Comment by Varunram** [comment]
I can't seem to find the video, sorry. If you can explain the issue over here, it'd be nice.

**Comment by AdrianMastronardi** [comment]
Essentially, I put songs on my playlist, hit play and it never reproduces the music.

**Comment by Varunram** [comment]
That's weird, definitely a bug. I'l take a look at it. Thanks!

**Comment by etaletai13** [comment]
Was this ever confirmed as a bug, or does @AdrianMastronardi have a problem on his end? Either way it should be updated/closed/otherwise not left hanging.

**Comment by Varunram** [comment]
As far as I see, play works fine on macOS (since I tested this on 10.13 a couple days back for release-1.01). I guess its a one time bug, so @AdrianMastronardi if you face this with the new wallet, please open a new issue. Thanks!

**Comment by etaletai13** [comment]
@Varunram this is the second time I've seen you respond to a bug with "works for me" - which has called attention to a severe need for CI and dev-ops structure in general. There is so much going on in this app that's being done in non-deterministic methods; it's no shocker that one test will succeed and one binary in the real world would fail. Personal tests by devs are Not sufficient tests, and this bug is a Bug. There's a need for better review than this, a big one. You also commented on seeing no benefit to Yarn over NPM. You'll find out why when my branch becomes the defacto method for this app; or you can start getting into studying new technologies and effective project management. Understand?

**Comment by etaletai13** [comment]
@AdrianMastronardi Thank you for the bug report, and I will seek it out and test until I find what's going on. And then fix it. And then credit that to You, for actually testing and reporting. I'd love to know if you can give a little more information about the binary you're using though.

**Comment by Varunram** [comment]
@etaletai13 Thanks for the concern - regarding the bug, let me respond. We ran extensive tests on wallet 1.0 before deploying and if you see carefully, bugs were a big issue with previous releases, so this time the testing flow was really smooth.

2. I didn't respond that yarn was better than npm, it was one of our developers @cryptofuture. I'd be more than willing to accept a PR which does make the transition, hence the bounty assigned.

3. Back to the issue at hand, I mentioned that it "may be a one time bug". If you did go through the code, you'd notice that the web app is loaded inside a window of the wallet. This means that the behaviour of the wallet is independent of the web app itself and the play button not working *might* be an issue on some devices (for which we do have an issue for on the web app's private repo).

4. Regarding general bug reports, all I (or anyone for that instance) can do is try to reproduce some of the bugs reported. If there are any log files attached, great, we can look into it. But this is an issue not pertaining to the inner functions of the wallet, so there will be no logs

5. If you're interested in contributing, you're more than welcome to do - that's one of the main reasons this is Open Source. If you can reproduce the bug, great, put in a PR for it and we shall review and accept it. Regarding CI, #173 exists in case you didn't notice that.

Regarding
> I'd love to know if you can give a little more information about the binary you're using though.
it is wallet v1.0 (its in the issue's title actually). If you can reproduce this, do let me know and I'll reopen the issue.

**Comment by etaletai13** [comment]
Well crap. Yes I did attribute a quote to you that was not yours. I definitely feel that the inconsistency needs to be handled, if a bug in a component than handled there; and if the bug is already reported there then I'll see if I can help at all. I'm working currently on the Yarn transition; which should get rid of Bower as well in the end. It'll be deterministic entirely. I had no idea about #173 and I'll contribute there as well however I can.

I support and use this thing, a lot! So I'm entirely concerned with it working out for the best. I'm just not great at being nice without editing extensively. That's a fault on me. I'll definitely attempt to isolate that bug, and at least have a failsafe.

**Comment by Varunram** [comment]
Awesome, looking forward to your PR! I'm looking at yarn vs npm meanwhile, to ensure I'm well educated. And regarding being nice, no problems, each one has their style of language :)

**Comment by etaletai13** [comment]
Thanks much for the understanding; and Yarn is quite the interesting thing to delve into. I think it will make our issue management much simplified, and improve the way Snyk functions. Plus, no need for global installs for the most part, might be able to kill all of those into just dev dependencies. Should be a good move, really, and none of the coders really need to know how it works if they aren't changing package.json.
