### ISSUE TITLE
[all] [1.5.0] [improvement] Build assumes binaries present on the machine.

### ISSUE THREAD

**Issue by etaletai13** [Musicoin/desktop#233]
1. Expected behaviour: `yarn global add https://github.com/Musicoin/desktop` should result in a ready-to-install app; or some kind of menu to do so, without any manual steps necessary, and no matter the configuration. 
4. What Happens: Currently we assume a number of things already present on the system, and even need to force installs. That's alright, we can get rid of that! So far, I've started in on making it so that you need only one of `npm` `yarn` or `git`, and can easily get it all going from there.

**Comment by etaletai13** [comment]
The building of go-musicoin is accomplished in one of my PRs, I intend to also split out the ux as a module, so that we can have alternates as well, and make it simple to make new ones.

**Comment by movingelectrons** [comment]
~/Projects/musicoin $ yarn global add https://github.com/Musicoin/desktop
yarn global v1.6.0
[1/4] Resolving packages...
error Error parsing JSON at "https://github.com/Musicoin/desktop/package.json", "Unexpected string in JSON at position 21573".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
jeromes@jtop ~/Projects/musicoin $ ls
desktop_old
jeromes@jtop ~/Projects/musicoin $ yarn global add https://github.com/movingelectrons/desktop
yarn global v1.6.0
[1/4] Resolving packages...
warning https://github.com/movingelectrons/desktop > @bower_components/mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning https://github.com/movingelectrons/desktop > mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning https://github.com/movingelectrons/desktop > @bower_components/mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning https://github.com/movingelectrons/desktop > mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning https://github.com/movingelectrons/desktop > @bower_components/mocha > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > findup-sync > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning https://github.com/movingelectrons/desktop > @bower_components/elliptical-dustjs > chokidar > readdirp > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > sinon > formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > wd > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
warning Pattern ["elliptical-utils@git+https://github.com/ellipticaljs/utils.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-utils-2.1.3-a465f394118578b9741452e1b874762c3438ed1f" as pattern ["elliptical-utils@ellipticaljs/utils#~2.1.2"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["jquery-extensions@git+https://github.com/ellipticaljs/jquery-extensions.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-jquery-extensions-1.0.15-c0a51b681b0ed476ac2bbf8cff6e0a7ca7ccede9" as pattern ["jquery-extensions@ellipticaljs/jquery-extensions#~1.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["jquery-mutation-summary@git+https://github.com/ellipticaljs/jquery-mutation-summary.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-jquery-mutation-summary-1.0.6-6d7984713841ed8cfa93287843d046fcca1dd818" as pattern ["jquery-mutation-summary@ellipticaljs/jquery-mutation-summary#~1.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["dustjs@git+https://github.com/ellipticaljs/dustjs.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-dustjs-2.7.11-2e29bf31386aa492dbecbfe05deb07c29ab94722" as pattern ["dustjs@ellipticaljs/dustjs#~2.7.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-template@git+https://github.com/ellipticaljs/template.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-template-1.0.15-18993eccec5fd25d9bc49d78ea71a610980eb3ff" as pattern ["elliptical-template@ellipticaljs/template#~1.0.2"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-dust-helpers@git+https://github.com/ellipticaljs/dust-helpers.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-dust-helpers-1.0.19-da1434de6d0c12031c0582c56756a58b4e23971f" as pattern ["elliptical-dust-helpers@ellipticaljs/dust-helpers#~1.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-class@git+https://github.com/ellipticaljs/class.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-class-1.0.9-7ab19ff4d2d7e8350eddc2f5d8954f0ce1539c54" as pattern ["elliptical-class@ellipticaljs/class#~1.0.7"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-mutation-summary@git+https://github.com/ellipticaljs/mutation-summary.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-mutation-summary-1.0.2-a749563edfcaf71ff039da4d22303cd9bfd3eec6" as pattern ["elliptical-mutation-summary@ellipticaljs/mutation-summary#~1.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["jquery@git+https://github.com/jquery/jquery-dist.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-jquery-3.3.1-9e8ec3d10fad04748176144f108d7355662ae75e" as pattern ["jquery@jquery/jquery-dist#>=1.6"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["md-ripple@git+https://github.com/EllipticalElements/md-ripple.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-md-ripple-1.0.1-f5114ff93a9075f06a667eedec6eba8555703324" as pattern ["md-ripple@EllipticalElements/md-ripple#~1.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["material-design-icons@git+https://github.com/ellipticaljs/material-design-icons.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-material-design-icons-2.0.0-cfd28c3a1aa97e7971226b2ecf2707f6be73b0bd" as pattern ["material-design-icons@ellipticaljs/material-design-icons#~2.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["component-extensions@git+https://github.com/ellipticaljs/component-extensions.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-component-extensions-1.1.3-582c40074b2c8d57b03f89074299400ee4af1ba4" as pattern ["component-extensions@ellipticaljs/component-extensions#~1.1.0"]. This could result in non-deterministic behavior, skipping.
info fsevents@0.3.8: The platform "linux" is incompatible with this module.
info "fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "https://github.com/movingelectrons/desktop > @bower_components/sinon-chai@2.14.0" has unmet peer dependency "sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0".
warning "https://github.com/movingelectrons/desktop > @bower_components/elliptical-dust-helpers > dustjs-helpers@1.7.4" has unmet peer dependency "dustjs-linkedin@2.7 - 2.8".
[4/4] Building fresh packages...
[1/6] ⢀ @bower_components/paper-autocomplete
[-/6] ⢀ waiting...
[3/6] ⢀ sauce-connect-launcher
[4/6] ⢀ paper-autocomplete
error /home/jeromes/.config/yarn/global/node_modules/@bower_components/paper-autocomplete: Command failed.
Exit code: 127
Command: bower i
Arguments:

**Comment by movingelectrons** [comment]
jeromes@jtop ~/Projects/musicoin $ yarn global add https://github.com/movingelectrons/desktop
yarn global v1.6.0
[1/4] Resolving packages...
warning https://github.com/movingelectrons/desktop > @bower_components/mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning https://github.com/movingelectrons/desktop > mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning https://github.com/movingelectrons/desktop > @bower_components/mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning https://github.com/movingelectrons/desktop > mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning https://github.com/movingelectrons/desktop > @bower_components/mocha > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > findup-sync > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning https://github.com/movingelectrons/desktop > @bower_components/elliptical-dustjs > chokidar > readdirp > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > sinon > formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
warning https://github.com/movingelectrons/desktop > @bower_components/web-component-tester > wd > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
warning Pattern ["elliptical-utils@git+https://github.com/ellipticaljs/utils.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-utils-2.1.3-a465f394118578b9741452e1b874762c3438ed1f" as pattern ["elliptical-utils@ellipticaljs/utils#~2.1.2"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["jquery-extensions@git+https://github.com/ellipticaljs/jquery-extensions.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-jquery-extensions-1.0.15-c0a51b681b0ed476ac2bbf8cff6e0a7ca7ccede9" as pattern ["jquery-extensions@ellipticaljs/jquery-extensions#~1.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["jquery-mutation-summary@git+https://github.com/ellipticaljs/jquery-mutation-summary.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-jquery-mutation-summary-1.0.6-6d7984713841ed8cfa93287843d046fcca1dd818" as pattern ["jquery-mutation-summary@ellipticaljs/jquery-mutation-summary#~1.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["dustjs@git+https://github.com/ellipticaljs/dustjs.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-dustjs-2.7.11-2e29bf31386aa492dbecbfe05deb07c29ab94722" as pattern ["dustjs@ellipticaljs/dustjs#~2.7.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-template@git+https://github.com/ellipticaljs/template.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-template-1.0.15-18993eccec5fd25d9bc49d78ea71a610980eb3ff" as pattern ["elliptical-template@ellipticaljs/template#~1.0.2"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-dust-helpers@git+https://github.com/ellipticaljs/dust-helpers.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-dust-helpers-1.0.19-da1434de6d0c12031c0582c56756a58b4e23971f" as pattern ["elliptical-dust-helpers@ellipticaljs/dust-helpers#~1.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-class@git+https://github.com/ellipticaljs/class.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-class-1.0.9-7ab19ff4d2d7e8350eddc2f5d8954f0ce1539c54" as pattern ["elliptical-class@ellipticaljs/class#~1.0.7"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["elliptical-mutation-summary@git+https://github.com/ellipticaljs/mutation-summary.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-elliptical-mutation-summary-1.0.2-a749563edfcaf71ff039da4d22303cd9bfd3eec6" as pattern ["elliptical-mutation-summary@ellipticaljs/mutation-summary#~1.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["jquery@git+https://github.com/jquery/jquery-dist.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-jquery-3.3.1-9e8ec3d10fad04748176144f108d7355662ae75e" as pattern ["jquery@jquery/jquery-dist#>=1.6"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["md-ripple@git+https://github.com/EllipticalElements/md-ripple.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-md-ripple-1.0.1-f5114ff93a9075f06a667eedec6eba8555703324" as pattern ["md-ripple@EllipticalElements/md-ripple#~1.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["material-design-icons@git+https://github.com/ellipticaljs/material-design-icons.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-material-design-icons-2.0.0-cfd28c3a1aa97e7971226b2ecf2707f6be73b0bd" as pattern ["material-design-icons@ellipticaljs/material-design-icons#~2.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["component-extensions@git+https://github.com/ellipticaljs/component-extensions.git"] is trying to unpack in the same destination "/home/jeromes/.cache/yarn/v1/npm-component-extensions-1.1.3-582c40074b2c8d57b03f89074299400ee4af1ba4" as pattern ["component-extensions@ellipticaljs/component-extensions#~1.1.0"]. This could result in non-deterministic behavior, skipping.
info fsevents@0.3.8: The platform "linux" is incompatible with this module.
info "fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "https://github.com/movingelectrons/desktop > @bower_components/sinon-chai@2.14.0" has unmet peer dependency "sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0".
warning "https://github.com/movingelectrons/desktop > @bower_components/elliptical-dust-helpers > dustjs-helpers@1.7.4" has unmet peer dependency "dustjs-linkedin@2.7 - 2.8".
[4/4] Building fresh packages...
[1/6] ⢀ @bower_components/paper-autocomplete
[-/6] ⢀ waiting...
[3/6] ⢀ sauce-connect-launcher
[4/6] ⢀ paper-autocomplete
error /home/jeromes/.config/yarn/global/node_modules/@bower_components/paper-autocomplete: Command failed.
Exit code: 127
Command: bower i
Arguments:

**Comment by etaletai13** [comment]
It looks like you've got global modules installed by bower, @movingelectrons. Try this first:
`rm -rf ~/.cache/yarn ~/.config/yarn/global` and then try `yarn` again.

It's almost always not needed or a good idea really to have global packages installed.

**Comment by movingelectrons** [comment]
tried rm -rf ~/.cache/yarn ~/.config/yarn/global, then again $ yarn global add https://github.com/movingelectrons/desktop , same error

**Comment by etaletai13** [comment]
@movingelectrons Looks like you're on linux and I'm on mac. Let me try some things and I'll get back to ya.

**Comment by movingelectrons** [comment]
I am, I am on debian 9.  Looking into making my desktop into a hackentosh or possibly getting a used macbook but I am short on funds ATM, that could change at any given moment though

**Comment by etaletai13** [comment]
@movingelectrons Mac of All Trades is amazing for used macbooks. I'm using one now, in fact. So I spun up a similar VM, and did a build. It still looks like you have some global packages from either yarn or npm. What you'll need to do is remove all of them, because they'll all interfere. It might help to take a look at the travis configuration on my repo to get an idea of what needs to be in place.

**Comment by etaletai13** [comment]
@movingelectrons Let me know your musicoin username, or your address, okay? I'll be adding a way to track contributions and do accordingly. And who cares where the thing lives!! Use what you'd like. Rename it to a specific name if you want to customize. Also send up a pr (to me) from getting it working!

**Comment by Varunram** [comment]
@etaletai13 @movingelectrons We'll be serving the ux module from the organisations' account itself (it'll happen shortly after I merge @etaletai13's PR on `yarn`), so you can have a central point to track all the changes related to the ux. I'm also thinking to announce a bounty program for various skins based on @etaletai13's PR, so you can give that a shot as well. Great stuff @etaletai13!

**Comment by etaletai13** [comment]
Should this issue be closed? It seems as such I believe.

**Comment by Varunram** [comment]
I guess, since we merged the yarn PR back in. Good point, need to do some housekeeping here.
