### ISSUE TITLE
[Windows 10 Home 64] [1.0.1] 32 bit  Wallet doesn't send funds

### ISSUE THREAD

**Issue by carrera888** [Musicoin/desktop#236]
1. Operating System: Windows 10 home x64
2. Screenshots: <attached>
3. Expected behaviour: Wallet should send funds
4. What Happens: Wallet return error message: Failed to send: Error: Unlocking account failed: Error: Invalid JSON RPC response: ""
5. Is any other Ethereum Wallet instance running in the background: No
![screen](https://user-images.githubusercontent.com/38737070/39272331-49dd9838-48e4-11e8-84f5-914dde2dff61.png)

**Comment by etaletai13** [comment]
I'm bumping this, so that we can get some eyes on it.

**Comment by Varunram** [comment]
I see, mostly the 32 bit wallet should've been packaged with the wrong `gmc` instance. Can someone with a  32 bit version of Windows check? I don't have one, so can't reproduce this issue myself.

**Comment by etaletai13** [comment]
That makes sense. I'll get a vm going from an old license somewhere, since I use a mac.

**Comment by innominatza** [comment]
can't sent to trade. it show Failed to send:Error:unlocking account failed:Error:could not decrypt key with given passphrase, can you help me?

**Comment by carrera888** [comment]
I repaired my wallet by full resetup 32 bit version. I transfer my funds and will never use musicoin wallet.

**Comment by etaletai13** [comment]
@innominatza Are you certain it is not an issue with the passphrase? That is the error message, should be looked at first.

**Comment by etaletai13** [comment]
@carrera888 it very much looks like your problem was one with your install of Windows, or a security setting related. Any and all crypto wallets will also experience similar problems. Holding in an exchange; bear in mind they hold the same way but it's not even your computer.

Just to bear things in mind; convenience is in opposition to functionality. So this is a difficult task overall, for everyone. It's worth it.
