### ISSUE TITLE
Help launching Musicoin wallet (v0.7)

### ISSUE THREAD

**Issue by 4coinz** [Musicoin/desktop#54]
Hi all:
Im having issues launching my desktop wallet for musicoin. I recently updated to v.7 from a previous version which I never had issues with. Now, when I open the application it just sits on the "looking for peers" screen forever and never syncs. Ive tried to add peers manually but I get nothing. Do I need to run something else in the background to get this to work or what? Any hints/help would be appreciated. Thanks!

**Comment by mc-andre** [comment]
Make sure you don't have other eth wallets running in the background. Check your internet connection and lift restrictions from firewall.

**Comment by 4coinz** [comment]
Added the client to my list of allowed programs and also turned off the firewall completely just to verify its not being blocked. Still a no go. Since it was an upgrade, did I need to move any files or folders over from my previous version? Ive updated desktop wallets before and never had an issue, not sure if this one required an extra step or two --

**Comment by mc-andre** [comment]
Have you tried adding bootstrap nodes instead? https://github.com/Musicoin/go-musicoin/wiki/Boostrap-enodes

**Comment by 4coinz** [comment]
When I manually add peers I get:

Failed to add peer: Error: connect ECONNREFUSED 127.0.0.1:8545

**Comment by mc-andre** [comment]
Try restarting the program. If the same problem persist, download our GMC v2.0 over at https://github.com/musicoin/go-musicoin. We are currently testing GMC v3.0 to improve peer discovery, which will be released sometime this week.

**Comment by 4coinz** [comment]
Still no luck -- ill keep an eye out for the new version later in the week and see what happens!

**Comment by ebrinkis** [comment]
Musicoin Wallet is incompatible with geth or ethereum wallet. If either of those are running, you will get the ECONNREFUSED error.

**Comment by Varunram** [comment]
Checkout the new wallet beta over at https://forum.musicoin.org/topic/144/musicoin-wallet-v0-8-testing to see if it helps. Final release coming soon!

**Comment by davesa1** [comment]
nothing works for me, mac version wont open , and the windows v08 and v07 both wont sync to nodes, and i get the errorconection 127.0.0.0 etc...

when are you going to fix these issues? it is a shame even ethereum have the same problems in syncing and nodes.

**Comment by Varunram** [comment]
@davesa1 The current releases has been thoroughly tested and is certified to work on all platforms. Please check FAQ to see for commonly faced issues.

**Comment by B4GER** [comment]
I have the same problem. 0.7 or the 0.8 testing versions both fail to launch. I'm on MacOS 10.13.3. When trying to launch the app, it does the 'magnify' animation over the icon, but the app never appears. This is frustrating because I'm mining MUSIC but my payouts don't show in earlier versions of the wallet and newer versions fail to launch at all. Switching back to mining ETH until I can get this figured out.

**Comment by Varunram** [comment]
Hey, could you try replacing the bin/ directory inside the package with the latest gmc release to see if it works? Thanks!

**Comment by B4GER** [comment]
Is there some instructions or something on how to do that Varunram?  I'm not a developer... Do I just replace bin/gmc with this  https://github.com/Musicoin/desktop/blob/master/bin/gmc/gmc  ?

**Comment by Varunram** [comment]
@B4GER sorry, could you replace your copy of bin/gmc with https://github.com/Musicoin/go-musicoin/releases?

**Comment by B4GER** [comment]
Ok well I don't know if I did this right, but what I did was download the "gmc-darwin-10.6-386" file from the link you sent me. I assumed that was the right file since it was the only darwin one (which I assumed was for macs) and the other one specified AMD64 and that didn't sound right since this is an Intel box. Since it downloaded as "gmc-darwin-10.6-386", I thought maybe it was the gmc binary, so I renamed it to gmc and dropped it in the bin/gmc directory. Started the wallet and just got a blank screen. I thought maybe it wasn't set to executable, so I ran chmod +x on the new 'gmc' file I just put in there and now the wallet has started, and it's showing that i am connected to 3 peers, but Last Block: is empty and not updating (like it has no blocks...prior to this change, it said it was on block 1,572,772) and my balance shows as 0.00...which I guess would make sense if it is not synced at all with the chain. 

Does any of this this sound right to you @Varunram ?  This was all done on the 0.7 version of the wallet btw since the 0.8 version won't even start for me.

**Comment by B4GER** [comment]
As an experiment, I did the same steps above with the 0.8 version and see the same issue. The icon does the little 'expansion' animation after you open it, but then no wallet app appears, even with the new gmc put into Contents/Resources/app.nw/bin/gmc

**Comment by Varunram** [comment]
@B4GER Replied to you at #138
