### ISSUE TITLE
Bounty: 100K+ MC to improve Musicoin Desktop Wallet

### ISSUE THREAD

**Issue by immartian** [Musicoin/desktop#55]
Musicoin Desktop Wallet(MDW) is an open source project to support end users to well transfer the currency($MUSIC) between different stops. It's been downloaded more than 40K copies since it's first released at Feb. 2017, a big proof that it's a useful tool. 

Unfortunately, the focus of core dev team has to be more on blockchain upgrading, web application development, and mobile/hardware partnership, etc, to make the ecosystem bigger and widely adopted by layers of stakeholders.  The efforts putting to MDW is very much eclipsed. 

It's time to call community to join and help develop a better MDW. After internal deliberation, we decided to open this opportunity to public:  We'd love to offer 100K as 1st round to call community developers to join this repo and help develop MDW together. The money is only one part, we wish to connect music loving developers to build a harmonious world by unleashing 8 Million+  musicians around the globe.  Furthermore, we are open to offer other rounds to upgrade the tool to higher levels. Keep in mind, your ideas will be rewarded as well, even not becoming reality. 

Our common goal is to make this tool more efficient to run on multiple platform, ease-of-use and highly reliable and keep it open to future creativity. It's easy to follow this post and sign up quickly to start the conversation and contribution. Join us today and you can make the change!

**Comment by cryptofuture** [comment]
Could you list what exactly MDW miss now, and what needs to be done?

**Comment by immartian** [comment]
Some aspects to be improved in this round:
- Faster discovery of peers and sync to $MUSIC blockchain
- Better user experience to manage their accounts(create, backup etc.)
- Show recent tx history
- Add a simple player to listen to music for free (under UBI scheme)

**Comment by cryptofuture** [comment]
@immartian Thanks.
I'll try to help in spare time, through I highly doubt i could do something significant or worth even small part of bounty. But this is looks interesting, after all I use MDW myself, will try.

**Comment by mc-andre** [comment]
We could also implement 2FA feature over the password feature in case people lose or forget it. It happened a few times in the community.

**Comment by immartian** [comment]
@cryptofuture feel free to fork and PR

**Comment by immartian** [comment]
https://github.com/Musicoin/desktop/pull/56

**Comment by vvinam** [comment]
2. social music on mobile + mobile player + mobile wallet

**Comment by muiscp2p** [comment]
Easy ~ Use of Peer-to-peer download technology and VPN encryption technology to form nodes can be across the firewall Peer-to-peer encryption transmission, to the key nodes to increase the price of small custom-paid incentives. Of course, you need to complete synchronization to settle.
100KMC thanks
0x5491d07ee3966440f02721c97b580e9439b3355f

**Comment by ruzanoff** [comment]
![music](https://user-images.githubusercontent.com/3948589/33565019-04e405c2-d92d-11e7-945b-d1667509014c.jpg)
About the player and the buttons already wrote, I want to add:
Dynamic font size and fields (address and amount)
Change themes (background) arrow in the corner <> (different music styles)
Musicoin Wallet v0.70 - link musicoin.org
QR code for copying to the mobile wallet

**Comment by adrianhartanto0** [comment]
is there progress status of what has and hasn't been done? I'm interested!

**Comment by immartian** [comment]
it's in working, you can join any time, we will reward any code contributors based on the level of participation.

**Comment by Varunram** [comment]
@adrianhartanto0 We are in the process of developing a more structured program which will award bounties based on issues. Stay tuned!

**Comment by carlosmrp90** [comment]
Canales individuales por cada artista. Enlaces rápidos de música para compartir en las redes sociales.
Musicoin Creo en ti!

**Comment by muiscp2p** [comment]
I'm sorry~  I can't say too much Because I am a country network blockade. If
you want to succeed must want to consider to prevent the project node
between a variety of transmission way to prevent possible in government
blockade project should serve the whole music industry such as music
education music software to music software ...The artist that service now
and future.

2017-12-13 13:25 GMT+08:00 carlosmrp90 <notifications@github.com>:

**Comment by jhart2** [comment]
Roger that. I'm in.

**Comment by devzer01** [comment]
hi, great start and love the idea that is fuelling it. discovered by searching for DAG sizes (unfortunately yet fortunately :),  backing you with 15MH/s as we speak. as a seasoned developer and part time product advocate, few things i noticed

- renaming your git repo to follow standards (musicoin <--) lower case and for wallet rather than desktop i suggest using wallet (for seo purposes) or desktop-and-wallet since its more than a wallet i believe 
- noticed that the etherium forks are kept in the bushes? any particular reason? public fork would increase visibility IMHO + gives someone the ability to quickly validate there is no surprises in the code. (not suggesting evil here)
- maybe integrate some QA in to release process, bugs in critical applications of a eco-system could hurt the image, in this case image is attached to monitary value 

kudus to @Varunram i think he is doing an amazing job. however take a moment to check your symlinks, or do a test install on a different mac before publishing releases, helps :)

**Comment by Varunram** [comment]
@devzer01 Thank you very much for the suggestions. Regarding the release process, yes, we have a few issues there due to the build ecosystem, which has now been shifted to web2exe (this should solve the wallet not starting on some OSes). The repo name should've been changed, but I think its due to practice that we have the "desktop" name (earlier, you could play songs from the wallet, it was more of a desktop app). And the wallet as such isn't a fork of ETH, but go-musicoin is, we could provide a diff to make things easier, I shall open an issue at the other repo for people to take a look at. And thanks for the compliments, its due to this amazing community that we keep moving forward!

**Comment by Varunram** [comment]
Closing this since the information has been ported to BOUNTY.md
